### PR TITLE
Duck-Type style time checking for Numpy ints

### PR DESCRIPTION
**Pull request by calclavia**
Referring to https://github.com/craffel/pretty-midi/issues/114

Numpy ints cannot be properly checked with `isinstance(value, int)` in Python 3.

### CODE REVIEW

**Comment by olemb** [comment]
Looks good. I think the best solution is to use `numbers` as you have done. We could convert them to normal ints and floats but I think it's OK to keep them as Numpy numbers. They should behave the same as normal numbers.

One thing though: checking against `numbers.Number` will also accept complex numbers. That's probably not very useful. Could you change it to `numbers.Real`?

This also makes my test for `long` redundant leaving us with only that one test, which is a nice improvement.

Should we do the same for the other attributes?

**Comment by calclavia** [comment]
@olemb I'm not very familiar with MIDO. I only changed the part that I use and have tested and I'm not sure about other attributes.

I'll change it to `numbers.Real`.

**Comment by olemb** [comment]
OK, no problem. I'll do the other attributes.

**Comment by olemb** [comment]
I've released 1.1.21 with support for Numpy for all attributes based on your implementation. I had trouble merging your pull request so I ended up making a new commit but I've credited you in the changelog.

Thank you for contributing this!

**Pull request closed without merging**
