### PR TITLE
Pass `block` parameter through in `MultiPort._receive()`

### PR DESCRIPTION
**Pull request by rec**
I saw this while going over the source!

I haven't actually encountered a problem due to what I perceive is an issue on this line - it might be the correct behavior for some reason I haven't figured out.

If it's right, let me know and I'll change the commit to be a comment explaining it.

Thanks for an excellent library!

### CODE REVIEW

**Comment by cjappl** [comment]
This seems good to me! not sure why it would be a parameter if it's going to be ignored.

**Comment by rec** [comment]
Ping!

**Comment by cjappl** [comment]
@olemb has been MIA for a little bit, he may be on vacation or something

**Comment by olemb** [comment]
Sorry for taking so long to get back to you!

That was indeed a mistake. Thanks for the fix!

**Comment by rec** [comment]
No problem at all, thanks for doing this!  :-)

**Pull request merged**
