### PR TITLE
Cleaned codebase using flake8. Also switched instances of Todo -> TODO

### PR DESCRIPTION
**Pull request by cjappl**
No functional changes were made, just layout/PEP8 formatting

### CODE REVIEW

**Comment by olemb** [comment]
Thanks!

**Comment by olemb** [comment]
One of the changes broke Python 2 support. I've fixed it in a57a99451c0be0e38bbb3b520fa2e59a6160d6a9.

**Comment by olemb** [comment]
I just remembered you can pass a tuple of types to `isinstance()`: d47ad03b49d4cc456c01efe436e7042c9abab4c5

(I also didn't like having the two functions inside an if/else so I rewrite it like this. I think it's a bit cleaner.)

Otherwise great commit. :)

**Comment by cjappl** [comment]
Awesome! Yeah highly recommend checking into using "flake8", you could even potentially include it in the pre-commit step of "Contributing" if you have such a document.

Also, do you know how I get added to "Contributors" on this project? Is that automatic by github? I'd love to say I've "officially" contributed! :)

**Pull request merged**
